version: 2
updates:
    - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      # Add Kodiak `merge.automerge_label`
      - "ship it!"
    - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      # Add Kodiak `merge.automerge_label`
      - "ship it!"