import type { Env } from "./types";

const POSTMARK_API = "https://api.postmarkapp.com/email";
const PAYPAL_IPN_LIVE = "https://ipnpb.paypal.com/cgi-bin/webscr";
const PAYPAL_IPN_SANDBOX = "https://ipnpb.sandbox.paypal.com/cgi-bin/webscr";

interface IpnDonation {
  firstName: string;
  lastName: string;
  email: string;
  amount: string;
  currency: string;
  txnId: string;
  custom: string;
}

/**
 * Parses a PayPal IPN POST body (form-urlencoded) into a donation.
 * Returns null unless `payment_status` is `Completed` (so pending/refunded
 * IPNs don't trigger a thank-you). All donor fields are optional — PayPal may
 * omit name/email for some guest checkouts, in which case we fall back in the
 * email builder.
 */
function parseIpn(rawBody: string): IpnDonation | null {
  const params = new URLSearchParams(rawBody);
  if (params.get("payment_status") !== "Completed") return null;

  return {
    firstName: params.get("first_name") ?? "",
    lastName: params.get("last_name") ?? "",
    email: params.get("payer_email") ?? "",
    amount: params.get("mc_gross") ?? "0.00",
    currency: params.get("mc_currency") ?? "USD",
    txnId: params.get("txn_id") ?? "",
    custom: params.get("custom") ?? "",
  };
}

// The donor-side `custom` value we set on every donate link (HomeHero.vue).
// Requiring it rejects stray/forged IPNs that weren't generated by our buttons.
const CUSTOM_PREFIX = "SoundSwitch-";

/** True if the IPN carries a `custom` value we recognize. */
function isOurCustom(custom: string): boolean {
  return custom.startsWith(CUSTOM_PREFIX);
}

// `env` is passed at call time; this tiny indirection keeps parseIpn pure-ish.
function Env_merchant(_env: Env): string | undefined {
  return undefined; // merchant check is applied in the handler via env directly
}

/**
 * Verifies a PayPal IPN by echoing it back to PayPal with `cmd=_notify-validate`.
 * PayPal responds with the body `VERIFIED` (or `INVALID`). This is the standard
 * IPN verification handshake and works on a Personal PayPal account — no Business
 * account or REST app required.
 */
export async function verifyIpn(rawBody: string, env: Env): Promise<boolean> {
  // Only "sandbox" uses the sandbox host. "live" (or unset) uses the live host.
  // Any other value is invalid and fails closed (the IPN is not verified).
  const mode = env.PAYPAL_IPN_MODE;
  if (mode !== "sandbox" && mode !== "live" && mode !== undefined && mode !== "") {
    console.error(`Invalid PAYPAL_IPN_MODE: ${mode}`);
    return false;
  }
  const endpoint = mode === "sandbox" ? PAYPAL_IPN_SANDBOX : PAYPAL_IPN_LIVE;
  const body = `cmd=_notify-validate&${rawBody}`;

  try {
    const res = await fetch(endpoint, {
      method: "POST",
      headers: { "content-type": "application/x-www-form-urlencoded" },
      body,
    });
    if (!res.ok) return false;
    const text = (await res.text()).trim();
    return text === "VERIFIED";
  } catch {
    return false;
  }
}

/** Builds the HTML thank-you email (logo + first/last name + amount + open-source note). */
export function buildThankYouHtml(p: {
  firstName: string;
  lastName: string;
  amount: string;
  currency: string;
  logoUrl: string;
}): string {
  const name =
    [p.firstName, p.lastName].filter(Boolean).join(" ").trim() || "friend";
  const amountLabel = `${p.amount} ${p.currency}`;
  return `<!doctype html>
<html lang="en">
  <head><meta charset="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Thank you for supporting SoundSwitch</title></head>
  <body style="margin:0; padding:0; background-color:#f4f6fb; font-family:'Segoe UI',Helvetica,Arial,sans-serif; color:#1f2733;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f6fb; padding:24px 0;">
      <tr><td align="center">
        <table role="presentation" width="600" cellpadding="0" cellspacing="0" style="width:600px; max-width:100%; background-color:#ffffff; border-radius:12px; overflow:hidden; box-shadow:0 4px 18px rgba(20,40,80,0.08);">
          <tr><td align="center" style="background:linear-gradient(135deg,#2b5cff 0%,#6a3bff 100%); padding:32px 24px;">
            <img src="${p.logoUrl}" alt="SoundSwitch" width="72" height="72" style="display:block; border:0;" />
          </td></tr>
          <tr><td style="padding:32px 36px 8px;">
            <h1 style="margin:0 0 12px; font-size:24px; line-height:1.3; color:#1f2733;">Thank you, ${name}!</h1>
            <p style="margin:0 0 16px; font-size:16px; line-height:1.6; color:#3a4658;">
              I'm genuinely touched that you chose to support <strong>SoundSwitch</strong> with a donation of
              <strong>${amountLabel}</strong>.
            </p>
            <p style="margin:0 0 16px; font-size:16px; line-height:1.6; color:#3a4658;">
              SoundSwitch is a free, open-source project built and maintained by volunteers in our spare time.
              Donations like yours are what keep it alive — they cover hosting, code-signing certificates, and the
              late nights that go into every release. Knowing that the tool is useful enough for someone to give
              back means more than I can put into words.
            </p>
            <p style="margin:0 0 24px; font-size:16px; line-height:1.6; color:#3a4658;">
              From the bottom of my heart, thank you for being part of the open-source community that makes
              projects like this possible. 💙
            </p>
            <p style="margin:0 0 8px; font-size:15px; line-height:1.6; color:#1f2733;">With gratitude,<br /><strong>The SoundSwitch team</strong></p>
          </td></tr>
          <tr><td style="padding:0 36px 32px;">
            <table role="presentation" cellpadding="0" cellspacing="0"><tr><td style="border-radius:8px; background-color:#2b5cff;">
              <a href="https://soundswitch.aaflalo.me" style="display:inline-block; padding:12px 22px; font-size:15px; font-weight:600; color:#ffffff; text-decoration:none;">Visit SoundSwitch</a>
            </td></tr></table>
          </td></tr>
          <tr><td style="padding:20px 36px; background-color:#f7f9fc; border-top:1px solid #eef1f6;">
            <p style="margin:0; font-size:12px; line-height:1.5; color:#8a94a6;">
              You're receiving this email because you made a donation to SoundSwitch. This is a transactional message
              and doesn't contain marketing. SoundSwitch is free and open-source software.
            </p>
          </td></tr>
        </table>
      </td></tr>
    </table>
  </body>
</html>`;
}

/** Sends the thank-you email via the Postmark API. */
export async function sendPostmarkThankYou(
  env: Env,
  payer: { firstName: string; lastName: string; email: string },
  amount: string,
  currency: string,
): Promise<void> {
  const siteHost = env.SITE_HOSTNAME || "https://soundswitch.aaflalo.me";
  const logoUrl = `${siteHost}/logo-icon.svg`;
  const html = buildThankYouHtml({ ...payer, amount, currency, logoUrl });
  const from = env.POSTMARK_FROM;
  if (!from) {
    throw new Error("POSTMARK_FROM secret is not configured");
  }

  const res = await fetch(POSTMARK_API, {
    method: "POST",
    headers: {
      "content-type": "application/json",
      accept: "application/json",
      "X-Postmark-Server-Token": env.POSTMARK_SERVER_TOKEN ?? "",
    },
    body: JSON.stringify({
      From: from,
      To: payer.email,
      Subject: "Thank you for supporting SoundSwitch!",
      HtmlBody: html,
      MessageStream: "outbound",
    }),
  });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`Postmark send failed: ${res.status} ${text}`);
  }
}

/**
 * Worker handler for `POST /api/paypal-ipn`.
 * Verifies the IPN with PayPal, then sends the thank-you email. Acknowledges
 * with `200` only after a successful send; a Postmark failure returns `500` so
 * PayPal retries the IPN (retry-safe). Replayed IPNs are de-duplicated by txn_id
 * via the optional `IPN_DEDUPE` KV, so the donor never gets a duplicate email.
 */
export async function handlePayPalIpn(
  request: Request,
  env: Env,
  _ctx: ExecutionContext,
): Promise<Response> {
  if (request.method !== "POST") {
    return new Response("Method Not Allowed", { status: 405 });
  }

  if (!env.POSTMARK_SERVER_TOKEN || !env.POSTMARK_FROM) {
    return new Response(
      JSON.stringify({ error: "Postmark secrets are not configured" }),
      {
        status: 503,
        headers: { "content-type": "application/json; charset=utf-8" },
      },
    );
  }

  // Dedupe KV is mandatory: replays must never send a duplicate email. If it's
  // unbound the worker can't guarantee idempotency, so refuse to process.
  if (!env.IPN_DEDUPE) {
    return new Response(
      JSON.stringify({ error: "IPN_DEDUPE KV binding is not configured" }),
      {
        status: 503,
        headers: { "content-type": "application/json; charset=utf-8" },
      },
    );
  }

  const rawBody = await request.text();

  // Apply the optional merchant-email guard here (parseIpn skips it by default).
  if (env.PAYPAL_MERCHANT_EMAIL) {
    const receiver = new URLSearchParams(rawBody).get("receiver_email") ||
      new URLSearchParams(rawBody).get("business") || "";
    if (
      receiver &&
      receiver.toLowerCase() !== env.PAYPAL_MERCHANT_EMAIL.toLowerCase()
    ) {
      return new Response(JSON.stringify({ received: true, ignored: true }), {
        status: 200,
        headers: { "content-type": "application/json; charset=utf-8" },
      });
    }
  }

  const verified = await verifyIpn(rawBody, env);
  if (!verified) {
    return new Response(JSON.stringify({ received: false }), {
      status: 200,
      headers: { "content-type": "application/json; charset=utf-8" },
    });
  }

  const donation = parseIpn(rawBody);
  if (donation && donation.email) {
    // Reject IPNs that weren't generated by our donate buttons (no SoundSwitch- custom).
    if (!isOurCustom(donation.custom)) {
      return new Response(JSON.stringify({ received: true, ignored: true }), {
        status: 200,
        headers: { "content-type": "application/json; charset=utf-8" },
      });
    }

    // Idempotent, retry-safe claim: register the txn_id BEFORE sending so a
    // Postmark-then-KV-failure or a concurrent replay can't send a duplicate.
    // The claim uses a unique nonce marker; if a key already exists (real
    // replay or in-flight duplicate) we skip sending and ack 200.
    if (donation.txnId) {
      const CLAIM = "claimed";
      const existing = await env.IPN_DEDUPE.get(donation.txnId);
      if (existing) {
        return new Response(JSON.stringify({ received: true, duplicate: true }), {
          status: 200,
          headers: { "content-type": "application/json; charset=utf-8" },
        });
      }
      await env.IPN_DEDUPE.put(donation.txnId, CLAIM, {
        expirationTtl: 60 * 60 * 24 * 7,
      });
    }

    try {
      await sendPostmarkThankYou(env, donation, donation.amount, donation.currency);
    } catch (err) {
      // Roll back the claim so PayPal's retry can attempt delivery again, then
      // return 500 to force the retry. (If the rollback itself fails we still
      // 500 — the 7-day TTL bounds any eventual stale key.)
      if (donation.txnId) {
        try {
          await env.IPN_DEDUPE.delete(donation.txnId);
        } catch {
          /* best-effort */
        }
      }
      console.error("donation thank-you email failed", err);
      return new Response(JSON.stringify({ received: false, email_failed: true }), {
        status: 500,
        headers: { "content-type": "application/json; charset=utf-8" },
      });
    }
  }

  return new Response(JSON.stringify({ received: true }), {
    status: 200,
    headers: { "content-type": "application/json; charset=utf-8" },
  });
}
