// Minimal inline-markdown parser for the nightly changelog lines produced by CI.
//
// Each line looks like:
//   * **fix**(*ci*) : validate all -Version components against the 16-bit limit [d8db0908](https://github.com/Belphemur/SoundSwitch/commit/d8db0908)
//
// We only need a handful of constructs: a leading bullet marker, **bold**,
// *italic*, and [text](url) links. A full markdown engine is intentionally
// avoided. Links are restricted to the SoundSwitch commit permalink shape so a
// malicious commit subject can never inject a javascript:/data: href.

export interface ChangelogToken {
  isLink: boolean
  isBold: boolean
  isItalic: boolean
  text: string
  href?: string
}

// Changelog links are generated by CI as commit permalinks; anything else in a
// commit subject must never become an anchor (javascript:/data: XSS vector).
const SAFE_LINK_PATTERN = /^https:\/\/github\.com\/Belphemur\/SoundSwitch\/commit\/[0-9a-f]{7,64}$/

export function isSafeHref(href: string | undefined): boolean {
  return !!href && SAFE_LINK_PATTERN.test(href)
}

// A leading bullet marker (`*` or `-`, with optional indentation) marks a
// changelog entry. The surrounding <li> already renders the visual bullet, so
// we strip it here to avoid a literal asterisk in the text.
function stripBulletMarker(line: string): string {
  return line.replace(/^\s*[-*]\s+/, '')
}

// Matches, in priority order: **bold**, *italic*, [text](url).
const INLINE_PATTERN = /(\*\*([^*]+)\*\*)|(\*([^*]+)\*)|(\[([^\]]+)\]\(([^)\s]+)\))/g

export function parseChangelogLine(line: string): ChangelogToken[] {
  const stripped = stripBulletMarker(line)
  const tokens: ChangelogToken[] = []
  const regex = new RegExp(INLINE_PATTERN.source, 'g')
  let lastIndex = 0
  let match: RegExpExecArray | null

  while ((match = regex.exec(stripped)) !== null) {
    if (match.index > lastIndex) {
      tokens.push({
        isLink: false,
        isBold: false,
        isItalic: false,
        text: stripped.slice(lastIndex, match.index),
      })
    }

    if (match[2] !== undefined) {
      tokens.push({ isLink: false, isBold: true, isItalic: false, text: match[2] })
    } else if (match[4] !== undefined) {
      tokens.push({ isLink: false, isBold: false, isItalic: true, text: match[4] })
    } else {
      const href = match[7]
      if (isSafeHref(href)) {
        tokens.push({ isLink: true, isBold: false, isItalic: false, text: match[6], href })
      } else {
        tokens.push({ isLink: false, isBold: false, isItalic: false, text: match[6] })
        tokens.push({ isLink: false, isBold: false, isItalic: false, text: ` (${href})` })
      }
    }

    lastIndex = regex.lastIndex
  }

  if (lastIndex < stripped.length) {
    tokens.push({
      isLink: false,
      isBold: false,
      isItalic: false,
      text: stripped.slice(lastIndex),
    })
  }

  return tokens
}
