//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoundSwitch.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoundSwitch.Localization.SettingsStrings", typeof(SettingsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play: {0}.
        /// </summary>
        internal static string activePlayback {
            get {
                return ResourceManager.GetString("activePlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rec: {0}.
        /// </summary>
        internal static string activeRecording {
            get {
                return ResourceManager.GetString("activeRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The audio file you selected to be used as notification can&apos;t be found. SoundSwitch switched the notification setting back to {0}..
        /// </summary>
        internal static string audioFileNotFound {
            get {
                return ResourceManager.GetString("audioFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio file not found.
        /// </summary>
        internal static string audioFileNotFoundCaption {
            get {
                return ResourceManager.GetString("audioFileNotFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Files.
        /// </summary>
        internal static string audioFiles {
            get {
                return ResourceManager.GetString("audioFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Settings.
        /// </summary>
        internal static string audioSettings {
            get {
                return ResourceManager.GetString("audioSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Settings.
        /// </summary>
        internal static string basicSettings {
            get {
                return ResourceManager.GetString("basicSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes are automatically saved.
        /// </summary>
        internal static string closeTooltip {
            get {
                return ResourceManager.GetString("closeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Default Communication Device.
        /// </summary>
        internal static string communicationsDevice {
            get {
                return ResourceManager.GetString("communicationsDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When checked, the &apos;Default Communication Device&apos; and &apos;Default Playback Device&apos; are switched together (useful for Skype, TeamSpeak, e.g.)..
        /// </summary>
        internal static string communicationsDeviceTooltip {
            get {
                return ResourceManager.GetString("communicationsDeviceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string connected {
            get {
                return ResourceManager.GetString("connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle through.
        /// </summary>
        internal static string cycleThrough {
            get {
                return ResourceManager.GetString("cycleThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All audio devices.
        /// </summary>
        internal static string cycleThroughOptionAllAudioDevices {
            get {
                return ResourceManager.GetString("cycleThroughOptionAllAudioDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only selected audio devices.
        /// </summary>
        internal static string cycleThroughOptionOnlySelectedAudioDevices {
            get {
                return ResourceManager.GetString("cycleThroughOptionOnlySelectedAudioDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose between which devices to switch. Either only between the selected or between all..
        /// </summary>
        internal static string cycleThroughTooltip {
            get {
                return ResourceManager.GetString("cycleThroughTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string disconnected {
            get {
                return ResourceManager.GetString("disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkeys.
        /// </summary>
        internal static string hotkeys {
            get {
                return ResourceManager.GetString("hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check to enable hotkeys..
        /// </summary>
        internal static string hotkeysTooltip {
            get {
                return ResourceManager.GetString("hotkeysTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep SoundSwitch&apos;s System Tray Icon.
        /// </summary>
        internal static string keepSystemTrayIcon {
            get {
                return ResourceManager.GetString("keepSystemTrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When checked, the System Tray Icon won&apos;t change when the &apos;Default Playback Device&apos; changes..
        /// </summary>
        internal static string keepSystemTrayIconTooltip {
            get {
                return ResourceManager.GetString("keepSystemTrayIconTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language will change after restarting SoundSwitch.
        ///Do you want to restart now?.
        /// </summary>
        internal static string languageRestartRequired {
            get {
                return ResourceManager.GetString("languageRestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need a restart.
        /// </summary>
        internal static string languageRestartRequiredCaption {
            get {
                return ResourceManager.GetString("languageRestartRequiredCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string notification {
            get {
                return ResourceManager.GetString("notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner.
        /// </summary>
        internal static string notificationOptionBanner {
            get {
                return ResourceManager.GetString("notificationOptionBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customized Sound Notification.
        /// </summary>
        internal static string notificationOptionCustomized {
            get {
                return ResourceManager.GetString("notificationOptionCustomized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Notification.
        /// </summary>
        internal static string notificationOptionNone {
            get {
                return ResourceManager.GetString("notificationOptionNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Notification.
        /// </summary>
        internal static string notificationOptionSound {
            get {
                return ResourceManager.GetString("notificationOptionSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toast Notification.
        /// </summary>
        internal static string notificationOptionToast {
            get {
                return ResourceManager.GetString("notificationOptionToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Notification.
        /// </summary>
        internal static string notificationOptionWindowsDefault {
            get {
                return ResourceManager.GetString("notificationOptionWindowsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Notification: The default windows tray pop-up.
        ///Sound Notification: Plays a sound on the switched Playback Device.
        ///Customized Sound Notification: Plays the specified sound on the switched Playback Device.
        ///Toast Notification: Uses a special form of the windows tray pop-up version.
        ///Banner: Uses a custom always-on-top frame, useful for in-game usage..
        /// </summary>
        internal static string notificationTooltip {
            get {
                return ResourceManager.GetString("notificationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback.
        /// </summary>
        internal static string playback {
            get {
                return ResourceManager.GetString("playback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording.
        /// </summary>
        internal static string recording {
            get {
                return ResourceManager.GetString("recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        internal static string selected {
            get {
                return ResourceManager.GetString("selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the sound file for the notification..
        /// </summary>
        internal static string selectSoundButtonTooltip {
            get {
                return ResourceManager.GetString("selectSoundButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start automatically with Windows.
        /// </summary>
        internal static string startWithWindows {
            get {
                return ResourceManager.GetString("startWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip on Hover.
        /// </summary>
        internal static string tooltipOnHover {
            get {
                return ResourceManager.GetString("tooltipOnHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For both Devices.
        /// </summary>
        internal static string tooltipOnHoverOptionBothDevices {
            get {
                return ResourceManager.GetString("tooltipOnHoverOptionBothDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Tooltip.
        /// </summary>
        internal static string tooltipOnHoverOptionNone {
            get {
                return ResourceManager.GetString("tooltipOnHoverOptionNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback Device.
        /// </summary>
        internal static string tooltipOnHoverOptionPlaybackDevice {
            get {
                return ResourceManager.GetString("tooltipOnHoverOptionPlaybackDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording Device.
        /// </summary>
        internal static string tooltipOnHoverOptionRecordingDevice {
            get {
                return ResourceManager.GetString("tooltipOnHoverOptionRecordingDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Beta versions.
        /// </summary>
        internal static string updateIncludeBetaVersions {
            get {
                return ResourceManager.GetString("updateIncludeBetaVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When checked, SoundSwitch will also check for pre-release versions on GitHub..
        /// </summary>
        internal static string updateIncludeBetaVersionsTooltip {
            get {
                return ResourceManager.GetString("updateIncludeBetaVersionsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install updates automatically.
        /// </summary>
        internal static string updateInstallAutomatically {
            get {
                return ResourceManager.GetString("updateInstallAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates are installed automatically without any prompts..
        /// </summary>
        internal static string updateInstallAutomaticallyTooltip {
            get {
                return ResourceManager.GetString("updateInstallAutomaticallyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never check for updates.
        /// </summary>
        internal static string updateNever {
            get {
                return ResourceManager.GetString("updateNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t update the program unless you do it manually..
        /// </summary>
        internal static string updateNeverTooltip {
            get {
                return ResourceManager.GetString("updateNeverTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify me when updates are available.
        /// </summary>
        internal static string updateNotify {
            get {
                return ResourceManager.GetString("updateNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoundSwitch will notify you when there is a new update available. When clicking on the notification, you&apos;ll get a popup downloading the update for you and asking if you want to install it..
        /// </summary>
        internal static string updateNotifyTooltip {
            get {
                return ResourceManager.GetString("updateNotifyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Settings.
        /// </summary>
        internal static string updateSettings {
            get {
                return ResourceManager.GetString("updateSettings", resourceCulture);
            }
        }
    }
}
