name: .NET

on:
  push:
    branches: [ dev, master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ dev, master ]
env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  # DOTNET_CLI_TELEMETRY_OPTOUT: true
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PROJECT_NAME: "SoundSwitch"
  ARCH: "win-x64"
  FRAMEWORK: "net5.0-windows"
  NODEJS: 14

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          all_but_latest: true
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            ci:
             - '.github/**/*.yml'
            SoundSwitch:
              - 'SoundSwitch*/**'
            node:
              - 'package.json'
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        if: steps.filter.outputs.SoundSwitch == 'true' || steps.filter.outputs.ci == 'true'
        with:
          dotnet-version: 5.0.x
      - name: Restore
        if: steps.filter.outputs.SoundSwitch == 'true' || steps.filter.outputs.ci == 'true'
        run: dotnet restore
      - name: Build
        if: steps.filter.outputs.SoundSwitch == 'true' || steps.filter.outputs.ci == 'true'
        run: dotnet build -c Release --no-restore ${{env.PROJECT_NAME}}/${{env.PROJECT_NAME}}.csproj
      - name: Test
        if: steps.filter.outputs.SoundSwitch == 'true' || steps.filter.outputs.ci == 'true'
        run: dotnet test -c Release --no-restore  --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}"
      - name: Upload test results
        if: steps.filter.outputs.SoundSwitch == 'true' || steps.filter.outputs.ci == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: dotnet-results-${{ matrix.dotnet-version }}
          path: TestResults-${{ matrix.dotnet-version }}
        # Use always() to always run this step to publish test results when there are test failures
      - name: Setup Node.js
        if: steps.filter.outputs.node == 'true'
        uses: actions/setup-node@v2
        with:
          node-version: ${{env.NODEJS}}
      - name: Cache node modules
        if: steps.filter.outputs.node == 'true'
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install semantic-release dependencies
        if: steps.filter.outputs.node == 'true'
        run: npm ci --prefer-offline --silent
      - name: Release dry run
        if: steps.filter.outputs.node == 'true'
        run: npx semantic-release -d

  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      ci: ${{ steps.filter.outputs.ci }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            ci:
              - '.github/**/*.yml'
              - 'SoundSwitch*/**'

  prerelease:
    needs: [ build, changes ]
    if: github.ref == 'refs/heads/dev' && needs.changes.outputs.ci == 'true'
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore
        run: dotnet restore -r ${{ env.ARCH }}
      - name: Fetch tags
        run: git fetch --tags --force
      - name: Calculate version
        id: devVersion
        run: .\devVersion.ps1
      - name: Build pre-release
        run: dotnet publish -c Beta --no-restore -r ${{ env.ARCH }} ${{ env.PROJECT_NAME }}\${{ env.PROJECT_NAME }}.csproj -p:AssemblyVersion="${{ steps.devVersion.outputs.version }}"
      - name: Set Env var from GitHub
        uses: rlespinasse/github-slug-action@v3.x
      - name: Zip Build ${{env.PROJECT_NAME}}-${{env.GITHUB_REF_SLUG}}
        run: tar cafv ${{env.PROJECT_NAME}}-${{env.GITHUB_REF_SLUG}}.zip -C ${{ env.PROJECT_NAME }}\bin\Beta\${{ env.FRAMEWORK }}\${{ env.ARCH }}\publish\ *
      - name: Upload Artifact
        run: curl -u "${{env.DAV_USER}}:${{env.DAV_PASS}}" -X PUT ${{env.DAV_SERVER}}/${{env.DAV_USER}}/${{env.PROJECT_NAME}}/${{env.PROJECT_NAME}}-${{env.GITHUB_REF_SLUG}}.zip --upload-file ${{env.PROJECT_NAME}}-${{env.GITHUB_REF_SLUG}}.zip
        env:
          DAV_USER: ${{secrets.DAV_USER}}
          DAV_PASS: ${{secrets.DAV_PASS}}
          DAV_SERVER: "https://nc.aaflalo.me/remote.php/dav/files"
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{env.NODEJS}}
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci --prefer-offline --silent
      - name: Notify about new dev release
        run: node devRelease.js "${{ secrets.DISCORD_WEBHOOK }}" "${{ steps.devVersion.outputs.version }}" "${{env.GITHUB_REPOSITORY_OWNER_PART}}/${{env.GITHUB_REPOSITORY_NAME_PART}}"

  prepare-release:
    needs: [ build, changes ]
    if: github.ref == 'refs/heads/master' &&  needs.changes.outputs.ci == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{env.NODEJS}}
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install semantic-release dependencies
        run: npm ci --prefer-offline --silent
      - name: Release
        run: npx semantic-release
